/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siperpus;

import com.mysql.jdbc.Connection;
import com.toedter.calendar.JDateChooser;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Noobman
 */
public class Eadmin2 extends javax.swing.JInternalFrame {

     Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel DTM;
  private String tgl;
    public Eadmin2() {
        initComponents();
          conn = MainClassKoneksi1.getKoneksi();
        DTM = (DefaultTableModel)tbemply.getModel();
        AutoNumber();
        tampil_data();
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbemply = new javax.swing.JTable();
        bAdd = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tfnm = new javax.swing.JTextField();
        cbp = new javax.swing.JComboBox<>();
        tfnip = new javax.swing.JTextField();
        cbg = new javax.swing.JComboBox<>();
        tfphn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taadrs = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        tbemply.setBackground(new java.awt.Color(51, 51, 51));
        tbemply.setForeground(new java.awt.Color(255, 255, 255));
        tbemply.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIP", "Position", "Name", "Gender", "Date", "Phone", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbemply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbemplyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbemply);

        bAdd.setBackground(new java.awt.Color(102, 102, 102));
        bAdd.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        bAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjimg/icons8_Plus_40px.png"))); // NOI18N
        bAdd.setText("New");
        bAdd.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        bAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bAdd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bAdd.setPreferredSize(new java.awt.Dimension(70, 25));
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        bDelete.setBackground(new java.awt.Color(102, 102, 102));
        bDelete.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        bDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjimg/icons8_Delete_40px.png"))); // NOI18N
        bDelete.setText("Delete");
        bDelete.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        bDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bDelete.setPreferredSize(new java.awt.Dimension(70, 25));
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        bUpdate.setBackground(new java.awt.Color(102, 102, 102));
        bUpdate.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        bUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjimg/icons8_Edit_Property_40px.png"))); // NOI18N
        bUpdate.setText("Update");
        bUpdate.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        bUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bUpdate.setMinimumSize(new java.awt.Dimension(70, 25));
        bUpdate.setPreferredSize(new java.awt.Dimension(70, 25));
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjimg/icons8_Save_40px.png"))); // NOI18N
        jButton3.setText("Save");
        jButton3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.setPreferredSize(new java.awt.Dimension(70, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 255));

        tfnm.setBackground(new java.awt.Color(51, 51, 51));
        tfnm.setFont(new java.awt.Font("Lao UI", 0, 11)); // NOI18N
        tfnm.setForeground(new java.awt.Color(255, 255, 255));
        tfnm.setMinimumSize(new java.awt.Dimension(4, 25));
        tfnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnmActionPerformed(evt);
            }
        });

        cbp.setBackground(new java.awt.Color(102, 102, 102));
        cbp.setFont(new java.awt.Font("Lao UI", 0, 11)); // NOI18N
        cbp.setForeground(new java.awt.Color(255, 255, 255));
        cbp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Director", "HRD", "Chef", "Sous Chef", "Waiter", "Cashier", " ", " " }));
        cbp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpActionPerformed(evt);
            }
        });

        tfnip.setBackground(new java.awt.Color(51, 51, 51));
        tfnip.setFont(new java.awt.Font("Lao UI", 0, 11)); // NOI18N
        tfnip.setForeground(new java.awt.Color(255, 255, 255));
        tfnip.setMinimumSize(new java.awt.Dimension(4, 25));

        cbg.setBackground(new java.awt.Color(102, 102, 102));
        cbg.setFont(new java.awt.Font("Lao UI", 0, 11)); // NOI18N
        cbg.setForeground(new java.awt.Color(255, 255, 255));
        cbg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));

        tfphn.setBackground(new java.awt.Color(51, 51, 51));
        tfphn.setFont(new java.awt.Font("Lao UI", 0, 11)); // NOI18N
        tfphn.setForeground(new java.awt.Color(255, 255, 255));
        tfphn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfphnActionPerformed(evt);
            }
        });

        taadrs.setBackground(new java.awt.Color(51, 51, 51));
        taadrs.setColumns(20);
        taadrs.setFont(new java.awt.Font("Lao UI", 0, 11)); // NOI18N
        taadrs.setForeground(new java.awt.Color(255, 255, 255));
        taadrs.setRows(5);
        jScrollPane2.setViewportView(taadrs);

        jLabel2.setFont(new java.awt.Font("Lao UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Date :");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel3.setFont(new java.awt.Font("Lao UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Phone :");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Lao UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Address :");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel6.setFont(new java.awt.Font("Lao UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Gender :");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel7.setFont(new java.awt.Font("Lao UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Name :");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel14.setFont(new java.awt.Font("Lao UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Position :");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel15.setFont(new java.awt.Font("Lao UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("NIP :");

        jDateChooser1.setBackground(new java.awt.Color(51, 51, 51));
        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnip, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnm, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbg, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfphn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfphn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnip, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnm, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbpActionPerformed

    private void tbemplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbemplyMouseClicked

           
        int i = tbemply.getSelectedRow();
        if (i > -1) {
            try {
                tfnip.setText(tbemply.getValueAt(i, 0).toString());
                cbp.setSelectedItem(tbemply.getValueAt(i, 1).toString());
                tfnm.setText(tbemply.getValueAt(i, 2).toString());
                cbg.setSelectedItem(tbemply.getValueAt(i, 3).toString());
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tbemply.getValueAt(i, 4).toString());
                jDateChooser1.setDate(date);
                tfphn.setText(tbemply.getValueAt(i, 5).toString());
                taadrs.setText(tbemply.getValueAt(i, 6).toString());
            } catch (ParseException ex) {
                Logger.getLogger(Eadmin2.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        jButton3.setEnabled(false);
    }//GEN-LAST:event_tbemplyMouseClicked

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
clear();
tampil_data();
AutoNumber();
jButton3.setEnabled(true);
    }//GEN-LAST:event_bAddActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
delete_data();
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
update_data();
jButton3.setEnabled(true);
    }//GEN-LAST:event_bUpdateActionPerformed

    private void tfnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnmActionPerformed

    private void tfphnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfphnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfphnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 add();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
if(jDateChooser1.getDate()!=null){
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
           tgl =format.format(jDateChooser1.getDate());
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange

    
     public void add() {
        try {
            
            conn = MainClassKoneksi1.getKoneksi();
//            Statement st = conn.createStatement();
            String sql = "INSERT INTO ms_employe VALUES (?,?,?,?,?,?,?)";
            try (PreparedStatement p = conn.prepareStatement(sql)) {
                p.setString(1, tfnip.getText());
                p.setString(2, cbp.getSelectedItem().toString());
                p.setString(3, tfnm.getText());
                p.setString(4, cbg.getSelectedItem().toString());
//                p.setString(5, dcdate.getDateFormatString());
                p.setString(5,tgl);
                p.setString(6, tfphn.getText());
                p.setString(7, taadrs.getText());
                System.out.println(sql);
                p.execute();
                AutoNumber();
                tampil_data();
                JOptionPane.showMessageDialog(this, "Input Data Success");

            }
        } catch (SQLException ex) {

            Logger.getLogger(Eadmin2.class.getName()).log(Level.SEVERE, null,
                    ex);
            JOptionPane.showMessageDialog(this, "error" + ex.toString(), "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void AutoNumber() {
        try {
            conn = MainClassKoneksi1.getKoneksi();
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM ms_employe ORDER BY nip_emply DESC";
            rs = st.executeQuery(sql);
            if (rs.next()) {
                String kode = rs.getString("nip_emply").substring(4);
                String AN = "" + (Integer.parseInt(kode) + 1);
                String Nol = "";

                if (AN.length() == 1) {
                    Nol = "000";
                }else if (AN.length() == 2) {
                    Nol = "00";
                } else if (AN.length() == 3) {
                    Nol = "0";
                } else if (AN.length() == 4) {
                    Nol = "";
                }
                tfnip.setText("1701"+Nol+AN);//sesuaikan variablenya disini saya menggunakan jtextfield1
            } else {
                tfnip.setText("1701001");//sesuaikan variablenya disini saya menggunakan jtextfield1
            }
            rs.close();

        } catch (Exception e) {
            e.printStackTrace();//penanganan masalah
        }
    }

    public void tampil_data() {
        DefaultTableModel model = new DefaultTableModel();
        tbemply.setModel(model);
        model.addColumn("NIP");
        model.addColumn("Position");
        model.addColumn("Name");
        model.addColumn("Gender");
        model.addColumn("Date");
        model.addColumn("Phone");
        model.addColumn("Address");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            conn = MainClassKoneksi1.getKoneksi();
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM ms_employe ORDER BY nip_emply DESC LIMIT 5";
//            String sql = "SELECT * FROM ms_food WHERE id_food IN(SELECT MAX(id_food) FROM ms_food)";
//             String sql = "SELECT * FROM ms_food ORDER BY id_food DESC LIMIT 5";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                Object[] o = new Object[7];
                o[0] = rs.getString("nip_emply");
                o[1] = rs.getString("pos_emply");
                o[2] = rs.getString("nm_emply");
                o[3] = rs.getString("gender_emply");
                o[4] = rs.getString("date_emply");
                o[5] = rs.getString("phn_emply");
                o[6] = rs.getString("adrs_emply");
                model.addRow(o);
            }
            rs.close();
        } catch (SQLException e) {
           JOptionPane.showMessageDialog(this, "error" + e.toString(), "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }

    }

    public void delete_data() {

        int ok = JOptionPane.showConfirmDialog(null, "Are you Sure ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (ok == 0) {
            try {
                conn = MainClassKoneksi1.getKoneksi();
                String sql = "delete from ms_employe where nip_emply='" +tfnip.getText()+"'";
                java.sql.PreparedStatement 
                stmt=conn.prepareStatement(sql);
                stmt.executeUpdate();
                clear();
                tampil_data();
                AutoNumber();
                JOptionPane.showMessageDialog(null, "Data has Sucessfull Delete");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "error" + e.toString(), "Error Code :", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    
     public void update_data() {
           
       try {
            conn = MainClassKoneksi1.getKoneksi();
            Statement st = conn.createStatement();
              String sql="UPDATE ms_employe SET nip_emply=?,pos_emply=?,nm_emply=?,gender_emply=?,date_emply=?,phn_emply=?,adrs_emply=? WHERE nip_emply='"+tfnip.getText()+"'";
            try (PreparedStatement p = conn.prepareStatement(sql)) {
                p.setString(1, tfnip.getText());
                p.setString(2, cbp.getSelectedItem().toString());
                p.setString(3, tfnm.getText());
                p.setString(4, cbg.getSelectedItem().toString());
//                p.setString(5, tfdate.getText());
                p.setString(5, tgl);
                p.setString(6, tfphn.getText());
                p.setString(7, taadrs.getText());
                System.out.println(sql);
                p.executeUpdate();
                tampil_data();
                AutoNumber(); 
                JOptionPane.showMessageDialog(this, "Update Menu Success");

            }
        } catch (SQLException ex) {

            Logger.getLogger(Radmin2.class.getName()).log(Level.SEVERE, null,
                    ex);
            JOptionPane.showMessageDialog(this, "error" + ex.toString(), "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }

     
     public void clear(){
        tfnip.setText("");tfnm.setText("");tfphn.setText(""); taadrs.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bUpdate;
    private javax.swing.JComboBox<String> cbg;
    private javax.swing.JComboBox<String> cbp;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taadrs;
    private javax.swing.JTable tbemply;
    private javax.swing.JTextField tfnip;
    private javax.swing.JTextField tfnm;
    private javax.swing.JTextField tfphn;
    // End of variables declaration//GEN-END:variables
}
