/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siperpus;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Noobman
 */
public class Radmin2 extends javax.swing.JInternalFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel DTM;
     
    public Radmin2() {
        initComponents();
        conn = MainClassKoneksi1.getKoneksi();
        DTM = (DefaultTableModel)tbmenu.getModel();
        AutoNumber();
        tampil_data();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbkategory = new javax.swing.JComboBox<>();
        tfidmenu = new javax.swing.JTextField();
        tfmenun = new javax.swing.JTextField();
        tfmenup = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbmenu = new javax.swing.JTable();
        bAdd = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Lao UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Menu Name :");
        jLabel1.setPreferredSize(new java.awt.Dimension(56, 25));

        jLabel6.setFont(new java.awt.Font("Lao UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ID Menu :");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel6.setPreferredSize(new java.awt.Dimension(38, 25));

        jLabel2.setFont(new java.awt.Font("Lao UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Kategory :");
        jLabel2.setPreferredSize(new java.awt.Dimension(44, 25));

        jLabel3.setFont(new java.awt.Font("Lao UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Price :");
        jLabel3.setPreferredSize(new java.awt.Dimension(24, 25));

        cbkategory.setBackground(new java.awt.Color(102, 102, 102));
        cbkategory.setFont(new java.awt.Font("Lao UI", 0, 11)); // NOI18N
        cbkategory.setForeground(new java.awt.Color(255, 255, 255));
        cbkategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Dessert", "Drink", "Snack" }));
        cbkategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkategoryActionPerformed(evt);
            }
        });

        tfidmenu.setEditable(false);
        tfidmenu.setBackground(new java.awt.Color(51, 51, 51));
        tfidmenu.setForeground(new java.awt.Color(255, 255, 255));
        tfidmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfidmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidmenuActionPerformed(evt);
            }
        });

        tfmenun.setBackground(new java.awt.Color(51, 51, 51));
        tfmenun.setForeground(new java.awt.Color(255, 255, 255));
        tfmenun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmenunActionPerformed(evt);
            }
        });

        tfmenup.setBackground(new java.awt.Color(51, 51, 51));
        tfmenup.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfmenun, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfidmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfmenup, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbkategory, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfidmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfmenun, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfmenup, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbkategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        tbmenu.setBackground(new java.awt.Color(51, 51, 51));
        tbmenu.setFont(new java.awt.Font("Lao UI", 0, 11)); // NOI18N
        tbmenu.setForeground(new java.awt.Color(255, 255, 255));
        tbmenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Menu", "Menu Name", "Category", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbmenu);

        bAdd.setBackground(new java.awt.Color(102, 102, 102));
        bAdd.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        bAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjimg/icons8_Plus_40px.png"))); // NOI18N
        bAdd.setText("New");
        bAdd.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        bAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bAdd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bAdd.setPreferredSize(new java.awt.Dimension(70, 25));
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        bDelete.setBackground(new java.awt.Color(102, 102, 102));
        bDelete.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        bDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjimg/icons8_Delete_40px.png"))); // NOI18N
        bDelete.setText("Delete");
        bDelete.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        bDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bDelete.setPreferredSize(new java.awt.Dimension(70, 25));
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        bUpdate.setBackground(new java.awt.Color(102, 102, 102));
        bUpdate.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        bUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjimg/icons8_Edit_Property_40px.png"))); // NOI18N
        bUpdate.setText("Update");
        bUpdate.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        bUpdate.setPreferredSize(new java.awt.Dimension(70, 25));
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjimg/icons8_Save_40px.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.setPreferredSize(new java.awt.Dimension(70, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(bAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbkategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbkategoryActionPerformed

    private void tbmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmenuMouseClicked
 int i = tbmenu.getSelectedRow();
        if (i > -1) {
            tfidmenu.setText(tbmenu.getValueAt(i, 0).toString());
            tfmenun.setText(tbmenu.getValueAt(i, 1).toString());
            cbkategory.setSelectedItem(tbmenu.getValueAt(i, 2).toString());
            tfmenup.setText(tbmenu.getValueAt(i, 3).toString());
            
        }
     
    }//GEN-LAST:event_tbmenuMouseClicked

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
      clear();
      AutoNumber();
    }//GEN-LAST:event_bAddActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
delete_data();

    }//GEN-LAST:event_bDeleteActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
update_data();

    }//GEN-LAST:event_bUpdateActionPerformed

    private void tfidmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidmenuActionPerformed
tfidmenu.enable(false);
    }//GEN-LAST:event_tfidmenuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        add();
        tampil_data();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfmenunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmenunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmenunActionPerformed

    public void add() {
        try {
            conn = MainClassKoneksi1.getKoneksi();
            Statement st = conn.createStatement();
            String sql = "INSERT INTO ms_food VALUES (?,?,?,?)";
            try (PreparedStatement p = conn.prepareStatement(sql)) {
                p.setString(1, tfidmenu.getText());
                p.setString(2, tfmenun.getText());
                p.setString(3, cbkategory.getSelectedItem().toString());
                p.setString(4, tfmenup.getText());
                System.out.println(sql);
                p.execute();
                AutoNumber();
                JOptionPane.showMessageDialog(this, "Create Menu Success");

            }
        } catch (SQLException ex) {

            Logger.getLogger(Radmin2.class.getName()).log(Level.SEVERE, null,
                    ex);
            JOptionPane.showMessageDialog(this, "error" + ex.toString(), "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void AutoNumber() {
        try {
            conn = MainClassKoneksi1.getKoneksi();
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM ms_food ORDER BY id_food DESC";
            rs = st.executeQuery(sql);
            if (rs.next()) {
                String kode = rs.getString("id_food").substring(3);
                String AN = "" + (Integer.parseInt(kode) + 1);
                String Nol = "";

                if (AN.length() == 1) {
                    Nol = "00";
                } else if (AN.length() == 2) {
                    Nol = "0";
                } else if (AN.length() == 3) {
                    Nol = "";
                }
                tfidmenu.setText("IF" + Nol + AN);//sesuaikan variablenya disini saya menggunakan jtextfield1
            } else {
                tfidmenu.setText("IF001");//sesuaikan variablenya disini saya menggunakan jtextfield1
            }
            rs.close();

        } catch (Exception e) {
            e.printStackTrace();//penanganan masalah
        }
    }

    public void tampil_data() {
        DefaultTableModel model = new DefaultTableModel();
        tbmenu.setModel(model);
        model.addColumn("ID Menu");
        model.addColumn("Menu Name");
        model.addColumn("Category");
        model.addColumn("Price");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            conn = MainClassKoneksi1.getKoneksi();
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM ms_food";
//            String sql = "SELECT * FROM ms_food WHERE id_food IN(SELECT MAX(id_food) FROM ms_food)";
//             String sql = "SELECT * FROM ms_food ORDER BY id_food DESC LIMIT 5";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                Object[] o = new Object[5];
                o[0] = rs.getString("id_food");
                o[1] = rs.getString("nm_food");
                o[2] = rs.getString("ktgry_food");
                o[3] = rs.getString("prc_food");
                model.addRow(o);
            }
            rs.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi Error");
        }

    }

    public void delete_data() {

        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (ok == 0) {
            try {
                conn = MainClassKoneksi1.getKoneksi();
                String sql = "delete from ms_food where id_food='" +tfidmenu.getText()+"'";
                java.sql.PreparedStatement 
                stmt=conn.prepareStatement(sql);
                stmt.executeUpdate();
                clear();
                tampil_data();
                JOptionPane.showMessageDialog(null, "Data has Sucessfull Delete");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Failed to Delete");
            }
        }
    }
    
     public void update_data() {
           
       try {
            conn = MainClassKoneksi1.getKoneksi();
            Statement st = conn.createStatement();
              String sql="UPDATE ms_food SET id_food=?,nm_food =?,ktgry_food=?,prc_food=? WHERE id_food='"+tfidmenu.getText()+"'";
            try (PreparedStatement p = conn.prepareStatement(sql)) {
               
                p.setString(1, tfidmenu.getText());
                p.setString(2, tfmenun.getText());
                p.setString(3, cbkategory.getSelectedItem().toString());
                p.setString(4, tfmenup.getText());
                System.out.println(sql);
                p.executeUpdate();
                tampil_data();
                JOptionPane.showMessageDialog(this, "Update Menu Success");

            }
        } catch (SQLException ex) {

            Logger.getLogger(Radmin2.class.getName()).log(Level.SEVERE, null,
                    ex);
            JOptionPane.showMessageDialog(this, "error" + ex.toString(), "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
    
     public void clear(){
        tfidmenu.setText("");tfmenun.setText("");tfmenup.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bUpdate;
    private javax.swing.JComboBox<String> cbkategory;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbmenu;
    private javax.swing.JTextField tfidmenu;
    private javax.swing.JTextField tfmenun;
    private javax.swing.JTextField tfmenup;
    // End of variables declaration//GEN-END:variables
}
